# Generated by Django 4.1.5 on 2023-03-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d2api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='character_class',
        ),
        migrations.AddField(
            model_name='item',
            name='class_type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='icon_url',
            field=models.CharField(default='', max_length=2083),
            preserve_default=False,
        ),
    ]
