# Generated by Django 4.1.5 on 2023-04-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d2api', '0002_remove_item_character_class_item_class_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='pve_recommendation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='pvp_recommendation',
            field=models.FloatField(default=0.0),
        ),
    ]
